apiVersion: batch/v1
kind: Job
metadata:
  name: build
  namespace: jenkins
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  activeDeadlineSeconds: 1200 # 10 minutes
  template:
    spec:
      imagePullSecrets:
        - name: docker-hub
      restartPolicy: Never
      shareProcessNamespace: true
      containers:
        - name: build
          image: docker.gladeos.net/kubit/build:2023.12.13.2215
          command:
            - /bin/sh
            - -c
            - |
              mkdir -p ~/.ssh &&
              cp /tmp/ssh/id_rsa ~/.ssh/id_rsa &&
              chmod 600 ~/.ssh/id_rsa &&
              sleep infinity
          volumeMounts:
            # - mountPath: /mnt/data
            #   name: git-repo-volume
            - mountPath: /mnt/data
              name: git-repo
            - mountPath: /var/run
              name: docker-socket-volume
            - name: ssh-keys-volume
              mountPath: "/tmp/ssh"
              readOnly: true
          env:
            - name: DOCKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dockerhub-credentials
                  key: DOCKER_USERNAME
            - name: DOCKER_PAT
              valueFrom:
                secretKeyRef:
                  name: dockerhub-credentials
                  key: DOCKER_PAT
            - name: NUGET_PACKAGES
              value: "/mnt/data/packages"
            - name: DOCKER_HOST
              value: unix:///var/run/user/1000/docker.sock
        - name: docker
          image: docker:dind-rootless
          args:
            - dockerd
            - --registry-mirror=https://docker.gladeos.net
            #- --registry-mirror=http://nexus-docker.nexus.svc.cluster.local:9901
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run
              name: docker-socket-volume
          env:
            - name: DOCKER_DRIVER
              value: overlay2
        - name: git-repo
          persistentVolumeClaim:
            claimName: git-repo
        - name: docker-socket-volume
          emptyDir: {}
        - name: ssh-keys-volume
          secret:
            secretName: git-client-keys
# kubectl create secret generic dockerhub-credentials --from-literal=DOCKER_USERNAME=docker-write --from-literal=DOCKER_PAT=
#dotnet run -- --repo git-server-service.jenkins.svc.cluster.local --branch main --image "docker-hosted.gladeos.net/amp/taskmanager" --project "Applications/MindMatrix.Applications.TaskManager2/src//MindMatrix.Applications.TaskManager.csproj"
